document.write("<ul>");
document.write("<li><a href='/index.html'>Index</a></li>");
document.write("<li><a href='/download.html'>Download</a></li>\n");
document.write("<li><a href='/tools.html'>Dev Tools</a></li> \n");
document.write("<li><a href='http://pragprog.com/titles/tpantlr2/the-definitive-antlr-4-reference'>Book</a></li> \n");
document.write("<li><a href='https://github.com/antlr/antlr4/blob/4.6/doc/index.md'>Doc</a></li>\n");
document.write("<li><a href='/about.html'>About ANTLR</a></li>\n");
document.write("<li><a href='/support.html'>Support</a></li>  \n");
document.write("<li><a href='https://github.com/antlr/antlr4/issues'>Bugs</a></li> \n");
document.write("<li><a href='http://www.antlr3.org'>V3</a></li>");
document.write("</ul>\n");
document.write("<small>&copy; Copyright ANTLR / Terence Parr</small>");
