document.write("<ul>");
document.write("<li class=''><a href='index.html'>Home</a></li>");
document.write("<li class=''><a href='download.html'>Download</a></li>");
document.write("<li class=''><a href=''>Resources</a>");
document.write("<ul>");
document.write("<li class=''><a href='http://www.antlr.org/wiki/display/ANTLR4/Getting+Started+with+ANTLR+v4'>Getting Started</a></li>");
document.write("<li class=''><a href='http://pragprog.com/book/tpantlr2/the-definitive-antlr-4-reference'>ANTLR v4 Book</a></li>");
document.write("<li class=''><a href='http://www.antlr.org/wiki/display/ANTLR4/ANTLR+4+Documentation'>Documentation</a></li>");
document.write("<li class=''><a href='api.html'>Runtime API</a></li>");
document.write("<li class=''><a href=''>Source</a></li>");
document.write("<li class=''><a href=''>FAQ</a></li>");
document.write("</ul></li>");
document.write("<li class=''><a href=''>About ANTLR</a></li>");
document.write("<li class=''><a href=''>StringTemplate Engine</a></li>");
document.write("<li class=''><a href=''>Support</a></li>");
document.write("<li class=''><a href=''>Bugs</a></li>");
document.write("<li class=''><a href=''></a></li>");
document.write("<li class=''><a href=''></a></li>");
document.write("<li class=''><a href=''></a></li>");
document.write("</ul>");
