document.write("<ul>");
document.write("<li><a href='/index.html'>Home</a></li>");
document.write("<li><a href='/download.html'>Download</a></li>");
document.write("<li>Resources");
document.write("<ul>");
document.write("<li><a href='https://github.com/antlr/antlr4/blob/master/doc/getting-started.md'>Getting Started</a></li>");
document.write("<li><a href='http://pragprog.com/titles/tpantlr2/the-definitive-antlr-4-reference'>ANTLR v4 Book</a></li>");
document.write("<li><a href='https://github.com/antlr/antlr4/blob/4.6/doc/index.md'>Documentation</a></li>");
document.write("<li><a href='/api'>Runtime API</a></li>");
document.write("<li><a href='http://pragprog.com/titles/tpantlr2/source_code'>Examples (from book)</a></li>");
document.write("<li><a href='https://github.com/antlr/antlr4'>Source</a></li>");
document.write("<li><a href='https://github.com/antlr/antlr4/blob/master/doc/faq/index.md'>FAQ</a></li>");
document.write("</ul></li>");
document.write("<li><a href='/about.html'>About ANTLR</a></li>");
document.write("<li><a href='/license.html'>License and contributions</a></li>");
document.write("<li><a href='/support.html'>Support</a></li>");
document.write("<li><a href='https://github.com/antlr/antlr4/issues'>Bugs</a></li>");
document.write("<li><a href='mailto:parrt@antlr.org?subject=[insert subject here]'>Contact</a></li>");
document.write("<li><a href='/credits.html'>Credits</a></li>");
document.write("<li><a href='http://www.stringtemplate.org'>StringTemplate engine</a></li>");
document.write("<li><a href='http://www.antlr3.org'>ANTLR v3</a></li>");
document.write("</ul>");
