document.write("<div id='sidebar'>");
document.write("<ul>");
document.write("<li class='active'><a href='#'>Donec sed odio dui</a></li>");
document.write("<li><a href='#'>Aenean lacinia bibendum</a></li>");
document.write("<li><a href='#'>Nulla sed consectetur</a></li>");
document.write("<li><a href='#'>Etiam porta sem malesuada</a></li>");
document.write("<li><a href='#'>Magna mollis euismod</a></li>");
document.write("<li><a href='#'>Nulla vitae elit libero</a></li>");
document.write("<li><a href='#'>Vivamus sagittis lacus vel</a></li>");
document.write("</ul>");
document.write("</div>");
